name: Angular Build and Deploy to prod branch

on:
  push:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: angular-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Jest tests
        run: npx jest --ci --runInBand

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Build Angular app to prod
        working-directory: angular-project
        run: npm install --legacy-peer-deps && npm run build:prod

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: angular-project/dist/crisortiz-githubpage/browser
          branch: prod  
          token: ${{ secrets.GH_TOKEN }}